component_depth: 4
exclude:
  - /src/main/java/suneido/intfc/database/DatabasePackage\.java
languages:
- name: java
  production:
    exclude:
      - /src/main/java/suneido/jsdi/.*\.java
  test:
    include:
      - /src/test/.*\.java
