/**
 * <p>
 * This is a placeholder package for Suneido compiled code generated by the
 * components in the {@link suneido.compiler} package.
 * </p>
 *
 * <p>
 * <strong>Please do not put add any "static" (<i>ie</i> persistent,
 * file-based) Java classes in this package.</strong> 
 * </p>
 *
 * @author Victor Schappert
 * @since 20140829
 */
package suneido.code;