package suneido.language.jsdi.tools;

import java.util.ArrayList;

/**
 * Class which produces automatically generated lines of code.
 * 
 * @author Victor Schapppert
 * @since 20130630
 */
abstract class LineEditor {

	//
	// DATA
	//

	private final String matchToken;
	protected final ArrayList<String> lines;

	//
	// CONSTRUCTORS
	//

	/**
	 * Makes a new line editor with the given match token.
	 * 
	 * @param matchToken
	 *            Match token used by {@link FileEditor} to find the insertion
	 *            point for the lines generated by this line editor.
	 */
	public LineEditor(String matchToken) {
		this.matchToken = matchToken;
		this.lines = new ArrayList<String>();
	}

	//
	// ACCESSORS
	//

	/**
	 * Return the match token used by {@link FileEditor} to find where to insert
	 * the generated lines.
	 * 
	 * @return Match token
	 */
	public final String getMatchToken() {
		return matchToken;
	}

	/**
	 * Generate and return the lines.
	 * 
	 * @return List of automatically-generated lines of code.
	 */
	public abstract ArrayList<String> makeLines();

	//
	// HELPERS
	//

	/**
	 * Add a string to the generated lines list.
	 * @param line Line to add
	 * @see #add(CharSequence)
	 */
	protected final void add(String line) {
		lines.add(line);
	}

	/**
	 * Add a string to the generated lines list.
	 * @param line Line to add
	 * @see #add(String)
	 */
	protected final void add(CharSequence line) {
		lines.add(line.toString());
	}

	//
	// STATIC HELPERS
	//

	/**
	 * Create an indent string.
	 * 
	 * @param count
	 *            Number of logical indents to generate.
	 * @return Indent string
	 */
	public static StringBuilder indent(int count) {
		StringBuilder result = new StringBuilder(4 * count);
		while (0 < count) {
			result.append("    ");
			--count;
		}
		return result;
	}

	/**
	 * Add double quotes around a character string.
	 * 
	 * @param str
	 *            String to quote.
	 * @return New StringBuilder containing the quoted value of {@code str}.
	 */
	public static StringBuilder quote(CharSequence str) {
		StringBuilder result = new StringBuilder(str.length() + 2);
		return result.append('"').append(str).append('"');
	}

	/**
	 * Generate a Doxygen {@code <dfn> ... </dfn>} tag wrapping the given
	 * string.
	 * @param str String to wrap
	 * @return {@code <dfn>[str]</dfn>}
	 */
	public static StringBuilder doxygenDfn(CharSequence str) {
		StringBuilder result = new StringBuilder(str.length() + 11);
		return result.append("<dfn>").append(str).append("</dfn>");
	}

	/**
	 * Generate a Doxygen {@code <dfn> ... </dfn>} tag wrapping the name of the
	 * given class string.
	 * @param clazz Class to wrap
	 * @return {@code <dfn>[clazz.getName()]</dfn>}
	 */
	public static <T> StringBuilder doxygenDfn(Class<T> clazz) {
		return doxygenDfn(clazz.getName());
	}
}